# Generated by Django 4.1.5 on 2023-02-01 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lists", "0005_alter_todoitem_checked_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="starred",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="starred",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
