# Generated by Django 5.2.3 on 2025-11-02 02:20

import django.db.models.deletion
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_todo_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='originating_todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='collect_items',
            field=models.BooleanField(default=False, verbose_name='Automatically collect items from other lists'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='collect_next_days',
            field=models.IntegerField(default=1, verbose_name='Collect items which are due in the next X days'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='collect_on',
            field=recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='Collect items on this schedule'),
        ),
    ]
