# Generated by Django 5.2.3 on 2025-11-02 03:12

from django.db import migrations

def forward_func(apps, schema_editor):
    todo_item_model = apps.get_model('lists', 'TodoItem')
    for todo_item in todo_item_model.objects.all():
        if not todo_item.originating_todo:
            todo_item.originating_todo = todo_item.list.all().first()
            todo_item.save()

def backward_func(apps, schema_editor):
    pass  # This is safe because the migration is only copying data and not removing/moving.

class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_todoitem_originating_todo_alter_todo_collect_items_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, backward_func),
    ]
